SELECT * 
FROM ( SELECT C.ID, C.NAME, SUM(OP.UNITS_SOLD) AS SUM  
    FROM CATEGORIES C, ORDERS_PRODUCTS OP, PRODUCTS P
    WHERE OP.PRODUCT_ID = P.ID AND P.ID_CATEGORIES = C.ID
    GROUP BY C.ID, C.NAME 
    ORDER BY SUM DESC 
)
WHERE ROWNUM < 5